Repository d-coder111/SpectrumOfPython, pull requests merged in 2024-10, with the labels that each got.

#2 updated_readme
  README.md
Labels: hacktoberfest-accepted

#3 Create memoryGame.py
  Games/memoryGame.py
Labels: hacktoberfest-accepted

#5 enhancements
  Game-Galore/README.md
  Game-Galore/guessing_game.py
  Game-Galore/text_adventure.py
Labels: hacktoberfest-accepted

#11 added chess game with readme file
  chess/code.py
  chess/readme.md
Labels: good first issue, hacktoberfest-accepted

#14 contributed :)
  Data Doodles/credit card detection/credit_card_fraud_detection (2).ipynb
  Utility Unleashed/alarm _clock.py
Labels: enhancement, hacktoberfest-accepted

#17 add voice controlled to do list added to utilities category
  Utility Unleashed/Voice-controlled to-do list/README.md
  Utility Unleashed/Voice-controlled to-do list/requirements.txt
  Utility Unleashed/Voice-controlled to-do list/src/main.py
Labels: enhancement, hacktoberfest-accepted

#19 [❇️❇️game improvement ❇️❇️]added the new feature in the guessing game
  Game-Galore/guessing_game.py
Labels: good first issue, hacktoberfest-accepted

#21 [Added Morse Code 🚀] : Added the morse code
  Game-Galore/AI-Animal-Guess/AI_Guess_Animal.py
  Game-Galore/AI-Animal-Guess/animals.json
Labels: good first issue, hacktoberfest-accepted

#27 Recreate_Sea_Battle_project
  Game-Galore/Sea_battle/README.md
  Game-Galore/Sea_battle/__pycache__/board.cpython-312.pyc
  Game-Galore/Sea_battle/__pycache__/game.cpython-312.pyc
  Game-Galore/Sea_battle/__pycache__/player.cpython-312.pyc
  Game-Galore/Sea_battle/__pycache__/ship.cpython-312.pyc
  Game-Galore/Sea_battle/ai.py
  Game-Galore/Sea_battle/battleship.py
  Game-Galore/Sea_battle/board.py
  Game-Galore/Sea_battle/client.py
  Game-Galore/Sea_battle/game.py
  Game-Galore/Sea_battle/game_save.json
  Game-Galore/Sea_battle/player.py
  Game-Galore/Sea_battle/requirement.txt
  Game-Galore/Sea_battle/server.py
  Game-Galore/Sea_battle/ship.py
Labels: hacktoberfest-accepted

#28 feat: Add New Game `TikTakToe`
  Game-Galore/tiktaktoe/.gitignore
  Game-Galore/tiktaktoe/README.md
  Game-Galore/tiktaktoe/requirements.txt
  Game-Galore/tiktaktoe/src/main.py
  Game-Galore/tiktaktoe/src/utils.py
Labels: hacktoberfest-accepted, Project Request
